FIRSTNAME_LOGIN = "Andry"
LASTNAME_LOGIN = "MyLastName"
EMAIL_LOGIN = "andrmytest1@gmail.com"
PASSWORD_LOGIN = "Mytest1"
EMAIL_LOGIN_FAIL = "andrmy@gmail.com"
PASSWORD_LOGIN_FAIL = "Myyyyyy"
ADRESS_LOGIN = "Selenium Framework, Research Triangle Park, North"
CITY_LOGIN = "New York"
ZIPCODE_LOGIN = 10001
MOBILE_LOGIN = 12345678901
ADRESS_ALIAS_LOGIN = "Andry’s address"
TEST_DRESSES = "Printed Summer Dress"
